const path = require("path");

const projectRoot = path.resolve(__dirname, "..", "..");

module.exports = {
  projectRoot,
  configDir: path.join(projectRoot, "config"),
  outputDir: path.join(projectRoot, "output"),
  rawOutputDir: path.join(projectRoot, "output", "raw"),
  enhancedOutputDir: path.join(projectRoot, "output", "enhanced"),
  feishuOutputDir: path.join(projectRoot, "output", "feishu"),
  dailyOutputDir: path.join(projectRoot, "output", "daily"),
  sourcesPath: path.join(projectRoot, "config", "sources.json"),
  categoriesPath: path.join(projectRoot, "config", "categories.json"),
  modelConfigPath: path.join(projectRoot, "config", "model.json"),
  userFocusPath: path.join(projectRoot, "config", "user_focus.json"),
  seenUrlsPath: path.join(projectRoot, "output", "raw", "seen_urls.json"),
  rawItemsPath: path.join(projectRoot, "output", "raw", "raw_items.json"),
  enhancedItemsPath: path.join(projectRoot, "output", "enhanced", "enhanced_items.json"),
  contentEnrichedItemsPath: path.join(projectRoot, "output", "enhanced", "content_enriched_items.json"),
  executionReportPath: path.join(projectRoot, "execution_report.md"),
  adapterReportPath: path.join(projectRoot, "adapter_report.md"),
  summaryReportPath: path.join(projectRoot, "summary_report.md"),
  contentFetchReportPath: path.join(projectRoot, "content_fetch_report.md"),
  aiSummaryTestReportPath: path.join(projectRoot, "ai_summary_test_report.md"),
  aiSummaryEvalReportPath: path.join(projectRoot, "ai_summary_eval_report.md"),
  aiSummaryQualityReviewReportPath: path.join(projectRoot, "ai_summary_quality_review_report.md"),
  feishuRenderCheckReportPath: path.join(projectRoot, "feishu_render_check_report.md"),
  feishuPayloadPreviewPath: path.join(projectRoot, "output", "feishu", "feishu_payload_preview.json"),
  feishuSyncPlanPath: path.join(projectRoot, "feishu_sync_plan.md"),
  feishuPreviewReportPath: path.join(projectRoot, "feishu_preview_report.md"),
  feishuDryRunReportPath: path.join(projectRoot, "feishu_dry_run_report.md"),
  feishuTestSyncReportPath: path.join(projectRoot, "feishu_test_sync_report.md"),
  feishuSyncModeReportPath: path.join(projectRoot, "feishu_sync_mode_report.md"),
  feishuCliCheckReportPath: path.join(projectRoot, "feishu_cli_check_report.md"),
  feishuCliSyncPlanPath: path.join(projectRoot, "feishu_cli_sync_plan.md"),
  feishuCliTestSyncReportPath: path.join(projectRoot, "feishu_cli_test_sync_report.md"),
  feishuCliBitableCheckReportPath: path.join(projectRoot, "feishu_cli_bitable_check_report.md"),
  feishuCliBitableTestReportPath: path.join(projectRoot, "feishu_cli_bitable_test_report.md"),
  feishuCliBitableStatePath: path.join(projectRoot, "output", "feishu", "feishu_cli_bitable_state.json"),
  feishuCliBitableFieldsPath: path.join(projectRoot, "output", "feishu", "cli_bitable_fields.json"),
  feishuCliBitableRecordsPath: path.join(projectRoot, "output", "feishu", "cli_bitable_records.json"),
  feishuCliBitableDailyDocLinkFieldPath: path.join(projectRoot, "output", "feishu", "cli_bitable_daily_doc_link_field.json"),
  feishuCliBitablePatchPath: path.join(projectRoot, "output", "feishu", "cli_bitable_daily_doc_link_patch.json"),
  dailySyncSummaryReportPath: path.join(projectRoot, "daily_sync_summary_report.md"),
  syncClosureReportPath: path.join(projectRoot, "sync_closure_report.md"),
  manualAcceptanceChecklistPath: path.join(projectRoot, "manual_acceptance_checklist.md"),
  productionReadinessReportPath: path.join(projectRoot, "production_readiness_report.md"),
  round11ReportPath: path.join(projectRoot, "round11_report.md"),
  logsDir: path.join(projectRoot, "logs"),
  autoRunReportPath: path.join(projectRoot, "auto_run_report.md")
};
